### PR TITLE
Lazy-load album images

### PR DESCRIPTION
**Pull request by minus7**
Lazy-load album images and caching optimizations for the Docker build. See the commit messages for more details.

### CODE REVIEW

**Comment by geraldwuhoo** [comment]
Thanks for the PR! These changes make sense to me. I will merge when I get time to test the changes and confirm everything looks good.

**Comment by minus7** [comment]
Would be great if you could tag a release after merging, so my instance can autoupdate

**Comment by geraldwuhoo** [comment]
LGTM, I'll go ahead and merge this. Just FYI, I have changed domains for most of my services, so if you're using `registry.geraldwu.com`, you'll have to update the image pointer. I'll update the README about it with more details after I update a few CI things to tag a new release.

**Comment by geraldwuhoo** [comment]
There should be a tagged release out with it now. The new image is at `registry.wuhoo.xyz/jerry/omgur`. Release notes here: https://gitlab.wuhoo.xyz/jerry/omgur/-/releases/v0.1.4. Thanks again for the PR!

**Pull request merged**
